### signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Sicrano",
    "email": "sicrano@gmail.com",
    "nickname": "Sic",
	"password": "123456"
}

### login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "fulana@gmail.com",
	"password": "123456"
}

### postImage
POST http://localhost:3003/images/post
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmYzU3N2JjLWM1YzctNGU3Ni1iNzQ3LWE5ZDE0NjQxNjE5NyIsImlhdCI6MTYxNDE4NjcwMiwiZXhwIjoxNjE0MTg3OTAyfQ.5zA5H-9NxmELSGOtrOymy85FaamcyO1Xg-cyUIfCtS4
Content-Type: application/json

{
    "subtitle": "Foto3",
    "author": "Fulano",
	"file": "link",
    "tags": ["natureza", "pb"],
    "collection": "álbum"
}

### getImageById
GET http://localhost:3003/images/get/295506f2-4a95-4663-8724-3a34e45d0d2a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmYzU3N2JjLWM1YzctNGU3Ni1iNzQ3LWE5ZDE0NjQxNjE5NyIsImlhdCI6MTYxNDE4NjcwMiwiZXhwIjoxNjE0MTg3OTAyfQ.5zA5H-9NxmELSGOtrOymy85FaamcyO1Xg-cyUIfCtS4

### addTag
POST http://localhost:3003/images/tag?newTag=férias&newTag=bicicleta&newTag=família
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmYzU3N2JjLWM1YzctNGU3Ni1iNzQ3LWE5ZDE0NjQxNjE5NyIsImlhdCI6MTYxNDEyMDI1NiwiZXhwIjoxNjE0MTIxNDU2fQ.fB5KQYJvgBMH2ZxAOXFQXhIsXHGGIaUxQOux-ieInUE

### delImageById
DELETE http://localhost:3003/images/del/db7d302e-84e2-4308-a5dc-a20ab60e0f77
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmYzU3N2JjLWM1YzctNGU3Ni1iNzQ3LWE5ZDE0NjQxNjE5NyIsImlhdCI6MTYxNDE5MzE1MSwiZXhwIjoxNjE0MTk0MzUxfQ.nhmjymvyAUOM8qopZUrAX8MqCtOH6fj1beJylTL_ys8