### signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Sicrano",
    "email": "sicrano@gmail.com",
    "nickname": "Sic",
	"password": "123456"
}

### login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "rafael@labenu.com",
	"password": "123456"
}

### postImage
POST http://localhost:3003/images/post
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwMGUxYjQ0LThjNGUtNDg1OC04NGFhLTVmN2I5OGVhMmJjMyIsImlhdCI6MTYxNTMxNTQzOCwiZXhwIjoxNjE1MzE2NjM4fQ.gaSTOB5uY1ArLSoU2SBh01_ruIh-mbUR0MW5oyToxcE
Content-Type: application/json

{
    "subtitle": "Foto outra",
	"file": "https://picsum.photos/id/8/200/300",
    "tags": ["selfie", "pb", "natureza"],
    "collections": ["1", "2", "3"]
}

### getImageById
GET http://localhost:3003/images/get/09903736-96d9-41c0-9ff5-2c92fdc1e49c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwMGUxYjQ0LThjNGUtNDg1OC04NGFhLTVmN2I5OGVhMmJjMyIsImlhdCI6MTYxNTIxODg5MCwiZXhwIjoxNjE1MjIwMDkwfQ.27p4SHs8o4dxBl-C0JmYbujPFTRiocPqU5swIZ7SKIg

### getAllImages
GET http://localhost:3003/images/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwMGUxYjQ0LThjNGUtNDg1OC04NGFhLTVmN2I5OGVhMmJjMyIsImlhdCI6MTYxNTIzNTgzMSwiZXhwIjoxNjE1MjM3MDMxfQ.x0pjjjg0yYMFwv29P9amEVuBvIOYblZDnQy1pizJqBI

### delImageById
DELETE http://localhost:3003/images/del/5a4fa913-be4e-4ab6-9aa1-6f3067b6272e
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwMGUxYjQ0LThjNGUtNDg1OC04NGFhLTVmN2I5OGVhMmJjMyIsImlhdCI6MTYxNTMxOTg2OCwiZXhwIjoxNjE1MzIxMDY4fQ.eCZNY5unhzF5fnUVR1xwrVLIPDJf3lz5vdycXCwWkAY

### postCollection
POST http://localhost:3003/collections/post
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ4MDUyYjlhLTBlMTQtNGZhOC1hY2VmLThmZGJmZWYwMDc1ZiIsImlhdCI6MTYxNDk1MjUwNiwiZXhwIjoxNjE0OTUzNzA2fQ.StgQmZFEK8sF9zf8KZZOqvlr5KTKONXmD_yxVOYLri4
Content-Type: application/json

{
    "title": "Álbum 04",
    "subtitle": "Fotos diversas"
}

### getAllCollections
GET http://localhost:3003/collections/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ4MDUyYjlhLTBlMTQtNGZhOC1hY2VmLThmZGJmZWYwMDc1ZiIsImlhdCI6MTYxNDk2NTQ1MiwiZXhwIjoxNjE0OTY2NjUyfQ.Qmak5JQg5TwlC8uiiNJs9-myh6kfOXwn6w9iHQUTY2s

### getCoLLectionById
GET http://localhost:3003/collections/get/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ4MDUyYjlhLTBlMTQtNGZhOC1hY2VmLThmZGJmZWYwMDc1ZiIsImlhdCI6MTYxNDk2NzQxMSwiZXhwIjoxNjE0OTY4NjExfQ.LIJqVJloa0H5MrewdANUQ5Bhgcbhb9sAGlsJ5A5GjKwgit

### delCollectionById
DELETE http://localhost:3003/collections/del/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwMGUxYjQ0LThjNGUtNDg1OC04NGFhLTVmN2I5OGVhMmJjMyIsImlhdCI6MTYxNTMxOTg2OCwiZXhwIjoxNjE1MzIxMDY4fQ.eCZNY5unhzF5fnUVR1xwrVLIPDJf3lz5vdycXCwWkAY

### addToCollection
POST http://localhost:3003/images/collection/1919d3e4-ca95-460d-8c53-dc79f0c6dc5f
    ?collection=2
    &collection=3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwMGUxYjQ0LThjNGUtNDg1OC04NGFhLTVmN2I5OGVhMmJjMyIsImlhdCI6MTYxNTE0NDU3OSwiZXhwIjoxNjE1MTQ1Nzc5fQ.XptBMA7Oezy1myBURm1OYEQszLtD3Op7cPrVjq0zjcY

### removeFromCollection
DELETE http://localhost:3003/images/collection/1919d3e4-ca95-460d-8c53-dc79f0c6dc5f
    ?collection=2
    &collection=3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwMGUxYjQ0LThjNGUtNDg1OC04NGFhLTVmN2I5OGVhMmJjMyIsImlhdCI6MTYxNTE0NTg2NiwiZXhwIjoxNjE1MTQ3MDY2fQ.LBYHqISZWfHw7i_vwLaDUw1wZt_8OFTPR2SOxz7uNag

### getImagesByTagId
GET http://localhost:3003/images/tag/36
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQwMGUxYjQ0LThjNGUtNDg1OC04NGFhLTVmN2I5OGVhMmJjMyIsImlhdCI6MTYxNTM5MTg2MSwiZXhwIjoxNjE1MzkzMDYxfQ.wURiWWrqH0Q5ajm_SYrkNwHirzG7wvDP1IxoDlmfiTs