### signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Sicrano",
    "email": "sicrano@gmail.com",
    "nickname": "Sic",
	"password": "123456"
}

### login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "fulana@gmail.com",
	"password": "123456"
}

### postImage
POST http://localhost:3003/images/post
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmYzU3N2JjLWM1YzctNGU3Ni1iNzQ3LWE5ZDE0NjQxNjE5NyIsImlhdCI6MTYxNDExMTk5MSwiZXhwIjoxNjE0MTEzMTkxfQ.ehceMw5wdrZwqcXAtrqG9b0y0D-12lwLmQcwExI4LA0
Content-Type: application/json

{
    "subtitle": "Foto2",
    "author": "Fulano",
    "date": "2021-02-23",
	"file": "link",
    "tags": ["pb", "selfie"],
    "collection": "álbum"
}

### getImageById
GET http://localhost:3003/images/get/e5b4dad6-1c2b-4912-a571-b3a870c42eae
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmYzU3N2JjLWM1YzctNGU3Ni1iNzQ3LWE5ZDE0NjQxNjE5NyIsImlhdCI6MTYxNDEwMzI5NSwiZXhwIjoxNjE0MTA0NDk1fQ.chkg8MS2_ulpu04GoDfgK4gsSHQOYGijLjUnVLL2LBU